---
- hosts: localhost

  tasks:
    - name: add an apt key of MongoDB
      become: yes
      apt_key:
        keyserver: keyserver.ubuntu.com
        # url: https://www.mongodb.org/static/pgp/server-3.6.asc
        id: 91FA4AD5
        state: present

    # - name: create list file for MongoDB
    #   command: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list

    - name: create list file for MongoDB
      become: yes
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
        state: present

    - name: Install mongodb
      become: yes
      apt:
        pkg: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - libssl1.0.0
        - mongodb-org-server

    - name: ensure mongodb is running and starts on boot
      service: name=mongod state=restarted enabled=true
      become: yes

    - name: Installing Python-Pip
      apt:
        pkg: python-pip
        state: latest

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest use_mirrors=no
