version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: EST
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - ssmirr
  ignore:
  - dependency-name: pkg
    versions:
    - 4.4.9
    - 4.5.0
    - 4.5.1
    - 5.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: simple-git
    versions:
    - 2.31.0
    - 2.32.0
    - 2.34.2
    - 2.35.0
    - 2.35.1
    - 2.35.2
    - 2.36.0
    - 2.36.1
    - 2.36.2
    - 2.37.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: ping
    versions:
    - 0.4.0
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: inquirer
    versions:
    - 7.3.3
  - dependency-name: dockerode
    versions:
    - 3.2.1
