- hosts: all 
  become: yes
  tasks:

    - name: Install basic tools
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - vim
        - build-essential
        - python-dev

    - name: Add ansible repository.
      apt_repository:
        repo: 'ppa:ansible/ansible'

    - name: Install required system packages.
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - ansible

