---
- hosts: all
  become: yes

  tasks:
    ######################
    ### Docker Bakelet ###
    ######################
    - name: Disable Firewall
      service: name=ufw state=stopped

    - name: Install HTTPS Apt Packages
      apt: name={{ item }} update_cache=yes
      with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip

    - name: Add Docker GPG Key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add Docker Repository
      apt_repository:
        repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state=present

    - name: Install Docker CE
      apt: name=docker-ce state=present update_cache=yes

    - name: Enable Docker at Startup
      service: name=docker state=started enabled=yes

    - name: add user mod to docker
      command: usermod -aG docker {{ ansible_user }}

    - name: install docker-py
      pip:
        name: docker-py
        state: latest

    ###################################
    ### Install Bridge dependencies ###
    ###################################
    - name: Create docker network
      docker_network:
        state: present
        name: shared_nw
        driver: bridge
        driver_options:
          com.docker.network.bridge.name: docker1
        ipam_options:
          subnet: '192.168.252.252/24'
          gateway: 192.168.252.252

    # TODO: find the interface configuration and update in /etc/network/interfaces
    - name: add enp0s8 interface to docker1 bridge
      command: sudo brctl addif docker1 enp0s8
      ignore_errors: yes

    ######################
    ### Docker config ###
    ######################
    - name: Ensure docker.service.d directory exists
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Add docker.conf file in docker.service.d
      blockinfile:
        path: /etc/systemd/system/docker.service.d/docker.conf
        create: yes
        block: |
            [Service]
            ExecStart=
            ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

    - name: Restart service docker
      service:
        name: docker
        state: restarted
