---
- hosts: localhost

  tasks:
    - name: Get host signatures and add to known_hosts.
      command: ssh-keyscan -H "{{ip}}"
      register: known_host_key

    - name: Remove previous VM with this ip from ansible server
      known_hosts: name="{{ip}}" state="absent"

      #- debug: msg="Signature is {{ known_host_key.stdout }}"
    - name: Register VM ip address to ansible server
      known_hosts: name="{{ip}}" key="{{known_host_key.stdout }}"
