- hosts: all
  tasks:

    - name: Install basic utils and build envs.
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - unzip
        - vim
        - build-essential
      become: yes

    - name: Install required system packages.
      apt: pkg={{ item }} state=present
      with_items:
        - python-dev
        - python-pip
        - python-setuptools
      become: yes

    - name: Set python as default python using alternatives
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python2
      become: yes

    # - name: Upgrade pip
    #   pip:
    #     name: pip
    #     executable: pip2
    #     extra_args: --upgrade --user
    #     version: 18

    # # long story: https://github.com/pypa/pip/issues/5240
    # - name: Remove old pip
    #   file:
    #     state: absent
    #     path: "/usr/bin/pip"
    #   become: yes

    # - name: Create symbolic link
    #   file:
    #     src: "{{ansible_env.HOME}}/.local/bin/pip"
    #     dest: /usr/bin/pip
    #     state: link
    #   become: yes

    # - name: Set pip as default pip using alternatives
    #   alternatives:
    #     name: pip
    #     link: /usr/bin/pip
    #     path: "{{ansible_env.HOME}}/.local/bin/pip"
    #     priority: 1000
    #   become: yes

    - name: fetch fix pip script
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: fix pip
      shell: python /tmp/get-pip.py --force-reinstall
      become: yes

    - stat: path="{{BAKER_SHARE_DIR}}/requirements.txt"
      register: file_exists

    - name: Install the project requirements
      pip:
        state: present
        executable: /usr/local/bin/pip
        requirements: "{{BAKER_SHARE_DIR}}/requirements.txt"
      when: file_exists.stat.exists == True
      become: yes
