---
- hosts: all
  become: yes

  tasks:
    - name: Ensure apt-transport-https is installed.
      apt: name=apt-transport-https state=present

    - name: Add Nodesource apt key.
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repositories for Node.js.
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - "deb https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main"
        - "deb-src https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main"

    - name: Install Node.js
      become: yes
      apt:
        pkg: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - nodejs
        - build-essential
